name: sync
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

env:
  IMDB_COOKIE_AT_MAIN: ${{ secrets.IMDB_COOKIE_AT_MAIN }}
  IMDB_COOKIE_UBID_MAIN: ${{ secrets.IMDB_COOKIE_UBID_MAIN }}
  IMDB_LIST_IDS: ${{ secrets.IMDB_LIST_IDS }}
  IMDB_USER_ID: ${{ secrets.IMDB_USER_ID }}
  TRAKT_CLIENT_ID: ${{ secrets.TRAKT_CLIENT_ID }}
  TRAKT_CLIENT_SECRET: ${{ secrets.TRAKT_CLIENT_SECRET }}
  TRAKT_USERNAME: ${{ secrets.TRAKT_USERNAME }}
  TRAKT_PASSWORD: ${{ secrets.TRAKT_PASSWORD }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.go-cache-paths.outputs.go-build }}
            ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Sync watchlist, lists and ratings
        run: go run cmd/imdb-trakt-sync/main.go
